version: "3"
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: my-syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data:/var/syncthing
    ports:
      - 127.0.0.1:8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
    restart: unless-stopped

  # nginx:
  #   image: "nginx:1.19"
  #   container_name: "nginx"
  #   network_mode: "host"
  #   restart: "always"
  #   volumes:
  #     - "./configs/nginx/certs/:/etc/nginx/certs/"